// GENERATED by scripts/sync-suite.mjs - do not edit
export const ACCENT = "#e10600";
export const ACCENT_RGB = "225 6 0";      // space-separated, for rgb(... / a)
export const ACCENT_SOFT = "rgba(225, 6, 0, 0.14)";
