// GENERATED by scripts/sync-suite.mjs - do not edit
export const ACCENT = "#b00600";
export const ACCENT_RGB = "176 6 0";      // space-separated, for rgb(... / a)
export const ACCENT_SOFT = "rgba(176, 6, 0, 0.14)";
