// GENERATED by scripts/sync-suite.mjs from macos/suite.config.json - do not edit
//
// The release contract per app. Change any of it in suite.config.json, which is
// also what generates SuiteConfig for the three binaries and what
// bin/mirror-release.sh reads.
export const APP_CONTRACT = {
  "trove": {
    "tagPrefix": "",
    "macAsset": "Trove.zip",
    "minMacOS": "13",
    "status": "live"
  },
  "relay": {
    "tagPrefix": "relay-",
    "macAsset": "Relay.zip",
    "minMacOS": "13",
    "status": "live"
  },
  "tend": {
    "tagPrefix": "tend-",
    "macAsset": "Tend.zip",
    "minMacOS": "14",
    "status": "live"
  }
} as const;
