// GENERATED by scripts/sync-suite.mjs - do not edit
export const VERSIONS = {
  "trove": {
    "version": "1.13.0",
    "releaseDate": "2026-09-05"
  },
  "relay": {
    "version": "0.1.0",
    "releaseDate": "2026-07-10"
  },
  "tend": {
    "version": "0.11.0",
    "releaseDate": "2026-07-10"
  }
} as const;
