// GENERATED by scripts/sync-suite.mjs - do not edit
export const VERSIONS = {
  "trove": {
    "version": "1.13.0",
    "releaseDate": "2026-09-05"
  },
  "relay": {
    "version": "0.3.1",
    "releaseDate": "2026-09-13"
  },
  "tend": {
    "version": "0.13.1",
    "releaseDate": "2026-09-12"
  }
} as const;
