#!/usr/bin/env node
// Single source of truth for the version + release date shown across the
// site (footer, changelog, download page) for every app in the suite, AND
// for the brand accent color used across the whole site. Reads each app's
// own canonical version file and CHANGELOG.md, and writes
// lib/versions.generated.ts; reads brand.accent from ../macos/suite.config.json
// and writes lib/brand-tokens.generated.ts + patches the token values in
// app/globals.css. Run whenever an app ships a new version or the brand
// color changes:
//
//   node scripts/sync-suite.mjs
//
// Looks for ../macos, ../relay, ../tend relative to the site repo (the
// layout under ~/dev/trove where macos/, relay/, tend/, and site/ are
// siblings, each its own git repo). No network access, no dependencies.
//
// CI mode:
//
//   node scripts/sync-suite.mjs --from-releases
//
// The sibling checkouts only exist on a laptop. On a GitHub runner (and on
// Vercel) this repo is checked out alone, so the full pass above cannot run
// and lib/versions.generated.ts can only be refreshed by a human remembering
// to. It did not get remembered: v1.13.0 sat in macos/CHANGELOG.md for five
// days with VERSION still reading 1.12.8 and nothing anywhere said so.
//
// --from-releases needs no siblings. It asks the public release repo what the
// newest downloadable release for each app actually is. That makes the *published
// release* the authority, which is the right one for a marketing site: the
// number on the page can never claim a version a visitor cannot download.
// .github/workflows/sync-version.yml runs it daily and on demand.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { RELEASE_REPO } from "../lib/releases.ts";
import { changelogDate, publishedVersions } from "./suite-versions.ts";

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, "..");
const suiteRoot = resolve(siteRoot, "..");

function readTrimmed(path) {
  return readFileSync(path, "utf8").trim();
}

/** Pulls the date from the heading matching the app's canonical VERSION. */
function versionChangelogDate(changelogPath, version) {
  const text = readFileSync(changelogPath, "utf8");
  return changelogDate(text, version);
}

function requireFile(path, label) {
  if (!existsSync(path)) {
    console.error(`sync-suite: ${label} not found at ${path}`);
    process.exit(1);
  }
  return path;
}

const destPath = join(siteRoot, "lib", "versions.generated.ts");

function renderVersionsFile(versions) {
  return `// GENERATED by scripts/sync-suite.mjs - do not edit
export const VERSIONS = ${JSON.stringify(versions, null, 2)} as const;
`;
}

/** Reads the committed generated file back for the change summary. */
function readGeneratedVersions() {
  const text = readFileSync(destPath, "utf8");
  const body = text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1);
  return JSON.parse(body);
}

if (process.argv.includes("--from-releases")) {
  const res = await fetch(
    `https://api.github.com/repos/${RELEASE_REPO}/releases?per_page=100`,
    { headers: { Accept: "application/vnd.github+json" }, signal: AbortSignal.timeout(15_000) },
  );
  if (!res.ok) {
    console.error(`sync-suite: GitHub releases HTTP ${res.status}`);
    process.exit(1);
  }
  const list = await res.json();

  const versions = readGeneratedVersions();
  const next = publishedVersions(list);

  const before = readFileSync(destPath, "utf8");
  const after = renderVersionsFile(next);
  if (before === after) {
    console.log("sync-suite: all app versions are current");
    process.exit(0);
  }
  writeFileSync(destPath, after);
  for (const [app, release] of Object.entries(next)) {
    console.log(`sync-suite: ${app} ${versions[app].version} -> ${release.version} (${release.releaseDate})`);
  }
  process.exit(0);
}

// --- trove (macos) ---
const troveDir = join(suiteRoot, "macos");
const troveVersionPath = requireFile(
  join(troveDir, "VERSION"),
  "trove VERSION",
);
const troveChangelogPath = requireFile(
  join(troveDir, "CHANGELOG.md"),
  "trove CHANGELOG.md",
);
const troveVersion = readTrimmed(troveVersionPath);
const troveReleaseDate = versionChangelogDate(troveChangelogPath, troveVersion);
if (!troveReleaseDate) {
  console.error(`sync-suite: no dated heading found in ${troveChangelogPath}`);
  process.exit(1);
}

// --- relay ---
const relayDir = join(suiteRoot, "relay");
const relayVersionPath = requireFile(
  join(relayDir, "VERSION"),
  "relay VERSION",
);
const relayChangelogPath = requireFile(
  join(relayDir, "CHANGELOG.md"),
  "relay CHANGELOG.md",
);
const relayVersion = readTrimmed(relayVersionPath);
const relayReleaseDate = versionChangelogDate(relayChangelogPath, relayVersion);
if (!relayReleaseDate) {
  console.error(`sync-suite: no dated heading found in ${relayChangelogPath}`);
  process.exit(1);
}

// --- tend ---
const tendDir = join(suiteRoot, "tend");
const tendVersionPath = requireFile(
  join(tendDir, "VERSION"),
  "tend VERSION",
);
const tendChangelogPath = requireFile(
  join(tendDir, "CHANGELOG.md"),
  "tend CHANGELOG.md",
);
const tendVersion = readTrimmed(tendVersionPath);
const tendReleaseDate = versionChangelogDate(tendChangelogPath, tendVersion);
if (!tendReleaseDate) {
  console.error(`sync-suite: no dated heading found in ${tendChangelogPath}`);
  process.exit(1);
}

const VERSIONS = {
  trove: { version: troveVersion, releaseDate: troveReleaseDate },
  relay: { version: relayVersion, releaseDate: relayReleaseDate },
  tend: { version: tendVersion, releaseDate: tendReleaseDate },
};

writeFileSync(destPath, renderVersionsFile(VERSIONS));

console.log(`sync-suite: wrote ${destPath}`);
for (const [key, info] of Object.entries(VERSIONS)) {
  console.log(`  ${key}: ${info.version} (${info.releaseDate})`);
}

// --- brand tokens (accent red) ---
// suite.config.json brand.accent is the cross-surface source of truth
// (also consumed by the macOS Swift codegen). Everything on the site that
// needs the brand red as a JS/TS value imports from the generated file
// below instead of hardcoding the hex; app/globals.css's --color-accent
// tokens (the Tailwind @theme definitions consumed by bg-accent etc.) are
// patched in place from the same value so there is exactly one place to
// change the color: suite.config.json.

/** Parses a "#rrggbb" hex string into a space-separated "r g b" triplet. */
function hexToRgbTriplet(hex) {
  const clean = hex.replace(/^#/, "");
  const r = parseInt(clean.slice(0, 2), 16);
  const g = parseInt(clean.slice(2, 4), 16);
  const b = parseInt(clean.slice(4, 6), 16);
  return `${r} ${g} ${b}`;
}

const suiteConfigPath = requireFile(
  join(troveDir, "suite.config.json"),
  "suite.config.json",
);
const suiteConfig = JSON.parse(readFileSync(suiteConfigPath, "utf8"));
const accentHex = suiteConfig.brand.accent.toLowerCase();
const accentRgb = hexToRgbTriplet(accentHex);
const accentSoft = suiteConfig.brand.accentSoft;

const brandTokensOut = `// GENERATED by scripts/sync-suite.mjs - do not edit
export const ACCENT = "${accentHex}";
export const ACCENT_RGB = "${accentRgb}";      // space-separated, for rgb(... / a)
export const ACCENT_SOFT = "${accentSoft}";
`;

const brandTokensPath = join(siteRoot, "lib", "brand-tokens.generated.ts");
writeFileSync(brandTokensPath, brandTokensOut);
console.log(`sync-suite: wrote ${brandTokensPath}`);
console.log(`  accent: ${accentHex} (rgb ${accentRgb})`);

// Patch just the three --color-accent* value lines in the @theme block,
// leaving the rest of globals.css (including accent-3, the neutral
// graphite) untouched.
const globalsCssPath = join(siteRoot, "app", "globals.css");
const globalsCssBefore = readFileSync(globalsCssPath, "utf8");
const globalsCssAfter = globalsCssBefore
  .replace(
    /--color-accent:\s*#[0-9a-fA-F]{6};/,
    `--color-accent: ${accentHex};`,
  )
  .replace(
    /--color-accent-rgb:\s*[\d\s]+;/,
    `--color-accent-rgb: ${accentRgb};`,
  )
  .replace(
    /--color-accent-2:\s*#[0-9a-fA-F]{6};/,
    `--color-accent-2: ${accentHex};`,
  );
if (globalsCssAfter !== globalsCssBefore) {
  writeFileSync(globalsCssPath, globalsCssAfter);
  console.log(`sync-suite: patched ${globalsCssPath}`);
} else {
  console.log(`sync-suite: ${globalsCssPath} already up to date`);
}

// --- the per-app release contract ---
//
// tagPrefix, macAsset, minMacOS and status all exist in suite.config.json
// already, and all four were ALSO typed out on this side: the prefixes and
// asset names in lib/releases.ts, the floor and the status in lib/brand.ts.
// Four values, two hand-maintained copies each, and the last time they drifted
// the site advertised macOS 13 next to a Tend binary that refused to launch
// below 15. They are generated now, from the same file the three binaries read.
const contractOut = `// GENERATED by scripts/sync-suite.mjs from macos/suite.config.json - do not edit
//
// The release contract per app. Change any of it in suite.config.json, which is
// also what generates SuiteConfig for the three binaries and what
// bin/mirror-release.sh reads.
export const APP_CONTRACT = ${JSON.stringify(
  Object.fromEntries(
    ["trove", "relay", "tend"].map((k) => [
      k,
      {
        tagPrefix: suiteConfig.apps[k].tagPrefix,
        macAsset: suiteConfig.apps[k].macAsset,
        minMacOS: suiteConfig.apps[k].minMacOS,
        status: suiteConfig.apps[k].status,
      },
    ]),
  ),
  null,
  2,
)} as const;
`;

const contractPath = join(siteRoot, "lib", "suite.generated.ts");
writeFileSync(contractPath, contractOut);
console.log(`sync-suite: wrote ${contractPath}`);
