#!/usr/bin/env node
// Single source of truth for the version + release date shown across the
// site (footer, changelog, download page) for every app in the suite.
// Reads each app's own canonical version file and CHANGELOG.md, and writes
// lib/versions.generated.ts. Run whenever an app ships a new version:
//
//   node scripts/sync-suite.mjs
//
// Looks for ../macos, ../relay, ../tend relative to the site repo (the
// layout under ~/dev/trove where macos/, relay/, tend/, and site/ are
// siblings, each its own git repo). No network access, no dependencies.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, "..");
const suiteRoot = resolve(siteRoot, "..");

// tend/CHANGELOG.md's top heading carries no date (see the file), so its
// release date is a literal fallback rather than something parsed out.
const TEND_RELEASE_DATE_FALLBACK = "2026-07-10";

function readTrimmed(path) {
  return readFileSync(path, "utf8").trim();
}

/** Pulls the date out of the top `## [x.y.z] - YYYY-MM-DD` heading. */
function topChangelogDate(changelogPath) {
  const text = readFileSync(changelogPath, "utf8");
  const match = text.match(/^## \[[^\]]+\]\s*-\s*(\d{4}-\d{2}-\d{2})/m);
  return match ? match[1] : null;
}

function requireFile(path, label) {
  if (!existsSync(path)) {
    console.error(`sync-suite: ${label} not found at ${path}`);
    process.exit(1);
  }
  return path;
}

// --- trove (macos) ---
const troveDir = join(suiteRoot, "macos");
const troveVersionPath = requireFile(
  join(troveDir, "VERSION"),
  "trove VERSION",
);
const troveChangelogPath = requireFile(
  join(troveDir, "CHANGELOG.md"),
  "trove CHANGELOG.md",
);
const troveVersion = readTrimmed(troveVersionPath);
const troveReleaseDate = topChangelogDate(troveChangelogPath);
if (!troveReleaseDate) {
  console.error(`sync-suite: no dated heading found in ${troveChangelogPath}`);
  process.exit(1);
}

// --- relay ---
const relayDir = join(suiteRoot, "relay");
const relayVersionPath = requireFile(
  join(relayDir, "VERSION"),
  "relay VERSION",
);
const relayChangelogPath = requireFile(
  join(relayDir, "CHANGELOG.md"),
  "relay CHANGELOG.md",
);
const relayVersion = readTrimmed(relayVersionPath);
const relayReleaseDate = topChangelogDate(relayChangelogPath);
if (!relayReleaseDate) {
  console.error(`sync-suite: no dated heading found in ${relayChangelogPath}`);
  process.exit(1);
}

// --- tend ---
const tendDir = join(suiteRoot, "tend");
const tendProjectYmlPath = requireFile(
  join(tendDir, "project.yml"),
  "tend project.yml",
);
const tendProjectYml = readFileSync(tendProjectYmlPath, "utf8");
const tendVersionMatch = tendProjectYml.match(
  /MARKETING_VERSION:\s*"?([\d.]+)"?/,
);
if (!tendVersionMatch) {
  console.error(
    `sync-suite: MARKETING_VERSION not found in ${tendProjectYmlPath}`,
  );
  process.exit(1);
}
const tendVersion = tendVersionMatch[1];
// tend's CHANGELOG.md top heading has no date yet, fall back to the literal.
requireFile(join(tendDir, "CHANGELOG.md"), "tend CHANGELOG.md");
const tendReleaseDate = TEND_RELEASE_DATE_FALLBACK;

const VERSIONS = {
  trove: { version: troveVersion, releaseDate: troveReleaseDate },
  relay: { version: relayVersion, releaseDate: relayReleaseDate },
  tend: { version: tendVersion, releaseDate: tendReleaseDate },
};

const out = `// GENERATED by scripts/sync-suite.mjs - do not edit
export const VERSIONS = ${JSON.stringify(VERSIONS, null, 2)} as const;
`;

const destPath = join(siteRoot, "lib", "versions.generated.ts");
writeFileSync(destPath, out);

console.log(`sync-suite: wrote ${destPath}`);
for (const [key, info] of Object.entries(VERSIONS)) {
  console.log(`  ${key}: ${info.version} (${info.releaseDate})`);
}
